# Pegatron Platform modules

PEGATRON_FM_6256_BN_F_PLATFORM_MODULE_VERSION = 1.0.0

export PEGATRON_FM_6256_BN_F_PLATFORM_MODULE_VERSION

PEGATRON_FM_6256_BN_F_PLATFORM_MODULE = sonic-platform-pegatron-fm-6256-bn-f_$(PEGATRON_FM_6256_BN_F_PLATFORM_MODULE_VERSION)_amd64.deb
$(PEGATRON_FM_6256_BN_F_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-pegatron
$(PEGATRON_FM_6256_BN_F_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(PEGATRON_FM_6256_BN_F_PLATFORM_MODULE)_PLATFORM = x86_64-pegatron_fm_6256_bn_f-r0
SONIC_DPKG_DEBS += $(PEGATRON_FM_6256_BN_F_PLATFORM_MODULE)
SONIC_STRETCH_DEBS += $(PEGATRON_FM_6256_BN_F_PLATFORM_MODULE)

$(eval $(call add_extra_package,$(PEGATRON_FM_6256_BN_F_PLATFORM_MODULE)))
